// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	dao "github.com/lengzuo/fundflow/dao"
	mock "github.com/stretchr/testify/mock"
)

// TransactionsRepository is an autogenerated mock type for the TransactionsRepository type
type TransactionsRepository struct {
	mock.Mock
}

// Insert provides a mock function with given fields: ctx, user
func (_m *TransactionsRepository) Insert(ctx context.Context, user *dao.TransactionsModel) error {
	ret := _m.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for Insert")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *dao.TransactionsModel) error); ok {
		r0 = rf(ctx, user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewTransactionsRepository creates a new instance of TransactionsRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTransactionsRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *TransactionsRepository {
	mock := &TransactionsRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
